site_name: Vesta
nav:
    - Inicio: index.md
    - Instalación: instalacion.md
    - Ingreso: ingreso.md
    - Menús: menus.md
    - Conceptos: conceptos.md
    - Implementando: entries.md
    - Plugin WebLogic: plugin_weblogic.md
    - Plugin SOA: plugin_soa.md
    - Plugin OS: operating_system.md
    - Patches: patches.md
    - Notificaciones: notificaciones.md
    

theme: material
  
   
   
markdown_extensions: 
    - admonition    
