site_name: Vesta
pages:
    - Inicio: index.md
    - Conceptos: about.md
    - Instalación: 2instalacion.md
    - Ingreso: 3ingreso.md
    - Funciones básicas: 4funciones.md
    - Implementando: 5implementando.md
    - Entries: 6entries.md
    - Plugins: 7plugin_weblogic.md
    - Plugin SOA: 8plugin_soa.md
    - Patches: 9patches.md
    - Auditor: 10auditor.md
    - Notificaciones: 11notificaciones.md
    

theme: material
    
markdown_extensions: 
    - admonition    
